# Generated by Django 3.1.7 on 2021-04-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SnoParks',
            new_name='SnoPark',
        ),
    ]
