# Generated by Django 3.1.7 on 2021-04-08 07:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210407_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail_no', models.CharField(max_length=254)),
                ('trail_name', models.CharField(max_length=254)),
                ('trail_type', models.CharField(max_length=254)),
                ('rec_1', models.CharField(max_length=254)),
                ('rec_2', models.CharField(max_length=254)),
                ('data_sourc', models.CharField(max_length=254)),
                ('attributes', models.CharField(max_length=254)),
                ('nat_trail', models.BigIntegerField()),
                ('length_mil', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
