# Generated by Django 3.1.7 on 2021-04-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_trail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='attributes',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='nat_trail',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='rec_1',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='rec_2',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='trail_no',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='trail_type',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
