# Generated by Django 3.1.7 on 2021-04-08 07:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20210408_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
        ),
    ]
