# Generated by Django 3.1.7 on 2021-04-11 03:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20210408_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True)),
                ('age', models.BigIntegerField(null=True)),
                ('city', models.CharField(max_length=254, null=True)),
                ('state', models.CharField(max_length=254, null=True)),
                ('location', models.CharField(max_length=254, null=True)),
                ('month', models.CharField(max_length=254, null=True)),
                ('year', models.BigIntegerField()),
                ('activity', models.CharField(max_length=254, null=True)),
                ('cause_death', models.CharField(max_length=254, null=True)),
                ('desc', models.CharField(max_length=254, null=True)),
                ('link', models.CharField(max_length=254, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='RecPoint',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, null=True)),
                ('area', models.CharField(max_length=254)),
                ('actlist', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TrailJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='trail',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='data_sourc',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='nat_trail',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='rec_1',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='rec_2',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='trail_type',
        ),
        migrations.AlterField(
            model_name='trail',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trail',
            name='length_mil',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='trail_name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='TrailType',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ttype', models.CharField(max_length=100)),
                ('trails', models.ManyToManyField(through='map.TrailJoin', to='map.Trail')),
            ],
        ),
        migrations.AddField(
            model_name='trailjoin',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.trail'),
        ),
        migrations.AddField(
            model_name='trailjoin',
            name='trailtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.trailtype'),
        ),
        migrations.CreateModel(
            name='ActivJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.activity')),
                ('recpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.recpoint')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='points',
            field=models.ManyToManyField(through='map.ActivJoin', to='map.RecPoint'),
        ),
    ]
