# Generated by Django 3.1.7 on 2021-04-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20210411_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='length_mil',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='trail_name',
            field=models.CharField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='trail_no',
            field=models.CharField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='trailtype',
            name='trails',
            field=models.ManyToManyField(through='map.TrailJoin', to='map.Trail'),
        ),
    ]
