# Generated by Django 3.1.7 on 2021-04-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20210411_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='death',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trailtype',
            name='trails',
            field=models.ManyToManyField(through='map.TrailJoin', to='map.Trail'),
        ),
    ]
